apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
 name: github
 namespace: argo
spec:
 dependencies:
   - name: github-dep
     eventSourceName: github
     eventName: deploy
     filters:
       data:
         - path: headers.X-Github-Event
           type: string
           value:
             - push
         - path: body.ref
           type: string
           value:
             - refs/heads/main
 triggers:
   - template:
       name: github-workflow-trigger
       k8s:
         operation: create
         source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-
              spec:
                arguments:
                  parameters:
                    - name: commit-hash
                workflowTemplateRef:
                  name: cicd-template
          parameters:
            - src:
                dependencyName: github-dep
                dataKey: body.after
              dest: spec.arguments.parameters.0.value
     retryStrategy:
       steps: 2